Production 🚀
fellesdatakatalog/api-access-request pull request #4
Opened 2023-08-15 09:05 UTC by kleivane

2023-08-15 09:28 UTC, larsksy submitted a review, later dismissed

2023-08-15 10:06 UTC, valosnah requested changes

2023-08-15 10:06 UTC, valosnah commented on deploy/prod/kustomization.yaml
> +namespace: staging
namespace: prod

2023-08-15 18:09 UTC, kleivane commented on deploy/prod/kustomization.yaml
> +namespace: staging
4c19ee59fb57a5e0b60d7235664430245e226e53

2023-08-16 09:38 UTC, valosnah approved these changes

2023-08-16 09:39 UTC, merged